services:
  db:
    container_name: postgres
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/vol-pgdata:/var/lib/postgresql/data:rw"
    networks:
      - pg-network
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    volumes:
      - "./vol-pgadmin_data:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"
    networks:
      - pg-network
      
volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmin_data:
    name: vol-pgadmin_data

networks:
  pg-network:
    external: true

# I'm using VSCODE Extension *SQLTools* instead of pg-admin
